### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [harrison-bergeron/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/
The ampersand should be written as:
``&amp;``

https://github.com/harrison-bergeron/prj-rev-bwfs-dasmoto/blob/8c207647d21cce98f4ff43661dce962f68ae6243/Dasmotos/index.html#L5

**Comment by harrison-bergeron** [comment]
Resource reviewed. Thanks for the input!
