### ISSUE TITLE
Font-family

### ISSUE THREAD

**Issue by martoio** [harrison-bergeron/prj-rev-bwfs-dasmoto#3]
You can put the ``font-family`` on the ``html`` or ``body`` elements, that way you don't have to constantly specify the font for all the elements:

https://github.com/harrison-bergeron/prj-rev-bwfs-dasmoto/blob/8c207647d21cce98f4ff43661dce962f68ae6243/Dasmotos/resources/css/index.css#L2

**Comment by harrison-bergeron** [comment]
Resource reviewed. Thanks for the input!
